# Generated by Django 5.1.1 on 2024-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decounted_price', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('b', 'baby fashion'), ('f', 'fashion'), ('h', 'health & beauty'), ('e', 'electronics'), ('m', 'mens fashion'), ('w', 'women fashion')], max_length=20)),
            ],
        ),
    ]
