# Generated by Django 5.1.1 on 2024-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_product_model_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='category',
            field=models.CharField(choices=[('baby fashion', 'baby fashion'), ('health & beauty', 'health & beauty'), ('electronics', 'electronics'), ('mens fashion', 'mens fashion'), ('women fashion', 'women fashion')], max_length=20),
        ),
    ]
