# Generated by Django 5.1.1 on 2024-10-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
