# Generated by Django 5.1.1 on 2024-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_product_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
