# Generated by Django 5.1.1 on 2024-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_cart_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_model',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
