# Generated by Django 5.1.1 on 2024-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_cart_model_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_model',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
