# Generated by Django 5.1.1 on 2024-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_product_model_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='slug',
        ),
        migrations.AddField(
            model_name='product_model',
            name='slugg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
